server:
  port: 9201

spring:
  application:
    name: zuul-gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

zuul:
  host:
    connect-timeout-millis: 55000
    socket-timeout-millis: 60000
  routes:
    DATA-PROVIDER: /data-provider/**
    DATA-CONSUMER: /data-consumer/**

  ignored-patterns: /*-service/**
  sensitive-headers: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types[0]: text/xml
      mime-types[1]: application/xml
      mime-types[2]: application/json
      min-request-size: 2048
    response.enabled: true
