server:
  port: 8062

spring:
  application:
    name: data2
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true

eureka:
  instance:
    instance-id: data-8062
    prefer-ip-address: true

