server:
  port: 8061
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

#mybatis通过config-server进行配置

logging:
  level:
    root: info
  file:
    name: security-uaa.log
    max-size: 10MB
    max-history: 30
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

spring:
  application:
    name: data-provider
  #datasource通过config-server进行配置
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

