# User Account and Authentication
server:
  use-forward-headers: true
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
   application:
    name: security-uaa
   profiles:
     active:
       - dev
   main:
     allow-bean-definition-overriding: true
   http:
     encoding:
       enabled: true
       charset: utf-8
       force: true

logging:
  level:
    root: info
  file:
    name: security-uaa.log
    max-size: 10MB
    max-history: 30
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

info: 
  app.name: security-uaa
  company.name: www.klfront.com

#feign:
#  hystrix:
#    enabled: true
#  compression:
#    request:
#      enabled: true
#      mime-types[0]: text/xml
#      mime-types[1]: application/xml
#      mime-types[2]: application/json
#      min-request-size: 2048
#     response:
#       enabled: true

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.klfront.com:3306/klblog?useUnicode=true&characterEncoding=utf8
    username: xxxx
    password: xxxx
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true


---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.klfront.com:3306/klblog?useUnicode=true&characterEncoding=utf8
    username: xxxxx
    password: xxxxxx
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
